import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Box, Text, Divider, Stack, Heading } from '@chakra-ui/react'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Stack>
          <Heading>Welcome to Ready Set Bet!</Heading>
          <Text>Please proceed to Set Bet page.</Text>
        </Stack>
      </Box>
    </div>
  )
}
